<a href="https://colab.research.google.com/github/z-serra/PythonNotes4ML/blob/main/PandasNotes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Series

labels = ['a', 'b', 'c']
data = [1, 2, 3]
arr = np.array(data)
d = {'a': 1, 'b': 2, 'c': 3}

pd.Series(data=data)

0    1
1    2
2    3
dtype: int64

In [3]:
pd.Series(data=data, index=labels)

a    1
b    2
c    3
dtype: int64

In [4]:
pd.Series(data, labels)

a    1
b    2
c    3
dtype: int64

In [5]:
pd.Series(arr)

0    1
1    2
2    3
dtype: int64

In [6]:
pd.Series(arr, labels)

a    1
b    2
c    3
dtype: int64

In [7]:
pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [8]:
pd.Series(data=[sum, max, min])

0    <built-in function sum>
1    <built-in function max>
2    <built-in function min>
dtype: object

In [9]:
s1 = pd.Series([1, 2, 3, 4], ['A', 'B', 'C', 'D'])
s2 = pd.Series([1, 2, 6, 4], ['A', 'B', 'G', 'D'])
s1, s2

(A    1
 B    2
 C    3
 D    4
 dtype: int64,
 A    1
 B    2
 G    6
 D    4
 dtype: int64)

In [10]:
s1 + s2

A    2.0
B    4.0
C    NaN
D    8.0
G    NaN
dtype: float64

In [11]:
# Data Frame

from numpy.random import randn

np.random.seed(101)

In [12]:
df = pd.DataFrame(randn(3, 5), ['A', 'B', 'C'], ['X', 'Y', 'Z', 'Q', 'W'])
df

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [13]:
df['X']

A    2.706850
B   -0.319318
C    0.528813
Name: X, dtype: float64

In [14]:
# type(df['X'])
# pandas.core.series.Series

In [15]:
# type(df)
# pandas.core.frame.DataFrame

In [16]:
df.X

A    2.706850
B   -0.319318
C    0.528813
Name: X, dtype: float64

In [17]:
df[['X', 'W']]

          X         W
A  2.706850  0.651118
B -0.319318  0.740122
C  0.528813 -0.933237

In [18]:
df['New'] = df['X'] + df['W']
df

          X         Y         Z         Q         W       New
A  2.706850  0.628133  0.907969  0.503826  0.651118  3.357968
B -0.319318 -0.848077  0.605965 -2.018168  0.740122  0.420804
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237 -0.404424

In [19]:
# drop

df.drop('New', axis=1, inplace=True)
df

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [20]:
df.drop('C')

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122

In [21]:
df

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [22]:
# shape

df.shape

(3, 5)

In [23]:
# loc (location)

df.loc['C']

X    0.528813
Y   -0.589001
Z    0.188695
Q   -0.758872
W   -0.933237
Name: C, dtype: float64

In [24]:
# iloc (index location)

df.iloc[2]

X    0.528813
Y   -0.589001
Z    0.188695
Q   -0.758872
W   -0.933237
Name: C, dtype: float64

In [25]:
df.loc['A', 'X']

np.float64(2.706849839399938)

In [26]:
df.loc[['A', 'C'], ['X', 'Z']]

          X         Z
A  2.706850  0.907969
C  0.528813  0.188695

In [27]:
df > 0

       X      Y     Z      Q      W
A   True   True  True   True   True
B  False  False  True  False   True
C   True  False  True  False  False

In [28]:
df[df > 0]

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
B       NaN       NaN  0.605965       NaN  0.740122
C  0.528813       NaN  0.188695       NaN       NaN

In [29]:
df[df > 0][['Q', 'W']]

          Q         W
A  0.503826  0.651118
B       NaN  0.740122
C       NaN       NaN

In [30]:
df[df['W'] > 0]

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122

In [31]:
df[df['W'] > 0]['Q']

A    0.503826
B   -2.018168
Name: Q, dtype: float64

In [32]:
df[df['W'] < 0]

          X         Y         Z         Q         W
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [33]:
df[df['W'] < 0]['Q']

C   -0.758872
Name: Q, dtype: float64

In [34]:
df

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [35]:
df[(df['X'] > 0) & (df['W'] < 0)]

          X         Y         Z         Q         W
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [36]:
df[(df['X'] > 0) | (df['W'] < 0)]

          X         Y         Z         Q         W
A  2.706850  0.628133  0.907969  0.503826  0.651118
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [37]:
# reset_index

df.reset_index()

  index         X         Y         Z         Q         W
0     A  2.706850  0.628133  0.907969  0.503826  0.651118
1     B -0.319318 -0.848077  0.605965 -2.018168  0.740122
2     C  0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [38]:
df['New Col'] = 'AB CD EF'.split()
df

          X         Y         Z         Q         W New Col
A  2.706850  0.628133  0.907969  0.503826  0.651118      AB
B -0.319318 -0.848077  0.605965 -2.018168  0.740122      CD
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237      EF

In [39]:
df.set_index('New Col', inplace=True)
df

                X         Y         Z         Q         W
New Col
AB       2.706850  0.628133  0.907969  0.503826  0.651118
CD      -0.319318 -0.848077  0.605965 -2.018168  0.740122
EF       0.528813 -0.589001  0.188695 -0.758872 -0.933237

In [40]:
# index levels

outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
index = pd.MultiIndex.from_tuples(list(zip(outside, inside)))
index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [41]:
df = pd.DataFrame(randn(6, 2), index, ['A', 'B'])
df

             A         B
G1 1  0.955057  0.190794
   2  1.978757  2.605967
   3  0.683509  0.302665
G2 1  1.693723 -1.706086
   2 -1.159119 -0.134841
   3  0.390528  0.166905

In [42]:
df.loc['G1'].loc[1].loc['A']

np.float64(0.9550565092637361)

In [43]:
df.index.names

FrozenList([None, None])

In [44]:
df.index.names = ['Groups', 'Numbers']
df

                       A         B
Groups Numbers
G1     1        0.955057  0.190794
       2        1.978757  2.605967
       3        0.683509  0.302665
G2     1        1.693723 -1.706086
       2       -1.159119 -0.134841
       3        0.390528  0.166905

In [45]:
# cross section
df.xs('G1')

                A         B
Numbers
1        0.955057  0.190794
2        1.978757  2.605967
3        0.683509  0.302665

In [46]:
df.xs(2, level='Numbers')

               A         B
Groups
G1      1.978757  2.605967
G2     -1.159119 -0.134841

In [47]:
df = pd.DataFrame({'A': [1, 2, np.nan], 'B': [3, np.nan, np.nan], 'C': [4, 5, 6]})
df

     A    B  C
0  1.0  3.0  4
1  2.0  NaN  5
2  NaN  NaN  6

In [48]:
# dropna

df.dropna()

     A    B  C
0  1.0  3.0  4

In [49]:
df.dropna(axis=1)

   C
0  4
1  5
2  6

In [50]:
df.dropna(thresh=2) # if at least 2 non-NaN vals

     A    B  C
0  1.0  3.0  4
1  2.0  NaN  5

In [51]:
df.fillna(value='VALUE')

       A      B  C
0    1.0    3.0  4
1    2.0  VALUE  5
2  VALUE  VALUE  6

In [52]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [53]:
# groupby
df = pd.DataFrame({'Company': ['GO', 'GO', 'MS', 'MS', 'FB', 'FB'],
        'Person': ['A', 'B', 'C', 'D', 'E', 'F'],
        'Sales': [200, 120, 140, 320, 340, 360]})
df

  Company Person  Sales
0      GO      A    200
1      GO      B    120
2      MS      C    140
3      MS      D    320
4      FB      E    340
5      FB      F    360

In [54]:
by_company = df.groupby('Company')
by_company.mean(numeric_only=True)

         Sales
Company
FB       350.0
GO       160.0
MS       230.0

In [55]:
by_company.sum(numeric_only=True)

         Sales
Company
FB         700
GO         320
MS         460

In [56]:
by_company.std(numeric_only=True)

              Sales
Company
FB        14.142136
GO        56.568542
MS       127.279221

In [57]:
by_company.count()

         Person  Sales
Company
FB            2      2
GO            2      2
MS            2      2

In [58]:
by_company.max()

        Person  Sales
Company
FB           F    360
GO           B    200
MS           D    320

In [59]:
by_company.min()

        Person  Sales
Company
FB           E    340
GO           A    120
MS           C    140

In [60]:
by_company.describe()

        Sales
        count   mean         std    min    25%    50%    75%    max
Company
FB        2.0  350.0   14.142136  340.0  345.0  350.0  355.0  360.0
GO        2.0  160.0   56.568542  120.0  140.0  160.0  180.0  200.0
MS        2.0  230.0  127.279221  140.0  185.0  230.0  275.0  320.0

In [61]:
by_company.describe().transpose()

Company              FB          GO          MS
Sales count    2.000000    2.000000    2.000000
      mean   350.000000  160.000000  230.000000
      std     14.142136   56.568542  127.279221
      min    340.000000  120.000000  140.000000
      25%    345.000000  140.000000  185.000000
      50%    350.000000  160.000000  230.000000
      75%    355.000000  180.000000  275.000000
      max    360.000000  200.000000  320.000000

In [62]:
left = pd.DataFrame({'key': ['K0', 'K1'], 'A': ['A0', 'A1'], 'B': ['B0', 'B1']})
right = pd.DataFrame({'key': ['K0', 'K1'], 'C': ['C0', 'C1'], 'D': ['D0', 'D1']})
pd.merge(left, right, how='inner', on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1

In [63]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'], 'key2': ['K0', 'K1', 'K0', 'K1'], 'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'], 'key2': ['K0', 'K0', 'K0', 'K0'], 'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']})
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [64]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [65]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [66]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [67]:
left = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']}, index=['K0', 'K1'])
right = pd.DataFrame({'C': ['C0', 'C1'], 'D': ['D0', 'D1']}, index=['K0', 'K2'])
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN

In [68]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2  NaN  NaN   C1   D1

In [69]:
df.head()

  Company Person  Sales
0      GO      A    200
1      GO      B    120
2      MS      C    140
3      MS      D    320
4      FB      E    340

In [70]:
df['Company'].unique()

array(['GO', 'MS', 'FB'], dtype=object)

In [71]:
df['Company'].nunique()

3

In [72]:
df['Company'].value_counts()

Company
GO    2
MS    2
FB    2
Name: count, dtype: int64

In [73]:
df['Sales'].sum()

np.int64(1480)

In [74]:
df['Sales'].apply(lambda x:x*2)

0    400
1    240
2    280
3    640
4    680
5    720
Name: Sales, dtype: int64

In [75]:
df['Company'].apply(len)

0    2
1    2
2    2
3    2
4    2
5    2
Name: Company, dtype: int64

In [76]:
df.columns

Index(['Company', 'Person', 'Sales'], dtype='object')

In [77]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [78]:
df.sort_values('Sales')

  Company Person  Sales
1      GO      B    120
2      MS      C    140
0      GO      A    200
3      MS      D    320
4      FB      E    340
5      FB      F    360

In [79]:
df.isnull()

   Company  Person  Sales
0    False   False  False
1    False   False  False
2    False   False  False
3    False   False  False
4    False   False  False
5    False   False  False

In [80]:
# pivot table
pt = pd.DataFrame({'A': ['q', 'q', 'q', 'w', 'w', 'w'],
        'B': ['one', 'one', 'two', 'two', 'one', 'one'],
        'C': ['x', 'y', 'x', 'y', 'x', 'y'],
        'D': [1, 2, 3, 4, 5, 6]})
pt.pivot_table(values='D', index=['A', 'B'], columns='C')

C        x    y
A B
q one  1.0  2.0
  two  3.0  NaN
w one  5.0  6.0
  two  NaN  4.0

In [81]:
# html

data = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')
data[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546

In [82]:
# sql

from sqlalchemy import create_engine
engine = create_engine('sqlite:///:memory:')
df.to_sql('table_1', engine)
sql_df = pd.read_sql('table_1', con=engine)
sql_df

   index Company Person  Sales
0      0      GO      A    200
1      1      GO      B    120
2      2      MS      C    140
3      3      MS      D    320
4      4      FB      E    340
5      5      FB      F    360

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Company  6 non-null      object
 1   Person   6 non-null      object
 2   Sales    6 non-null      int64
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes